name: CI

on:
  push:
    branches:
      - main  # Replace with your default branch name, e.g., 'master'
  pull_request:
    branches:
      - main  # Replace with your default branch name, e.g., 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-dotenv

    - name: Run tests
      run: |
        pytest
